add message when `ONE_PACKAGE` does not match

diff --git a/bin/build-package b/bin/build-package
--- a/bin/build-package
+++ b/bin/build-package
@@ -42,6 +42,8 @@ if [ "$FORCE_BUILD" = "1" ]; then
 fi
 
 if [ -n "$ONE_PACKAGE" ] && [ "$ONE_PACKAGE" != "$PACKAGE" ]; then
+	>&2 echo "ONE_PACKAGE is set to '$ONE_PACKAGE'"
+	>&2 echo "Does not match '$PACKAGE', aborting..."
 	:> ~/OPERATION_ABORTED
 	exit 0
 fi
